---
title: "Class 5: Data visualization with ggplot2"
author: "Jie"
format: pdf
---

#Our first plot

R has base graphics

```{r}
library(ggplot2)
```


```{r}
plot(cars)
```
```{r}
ggplot(mtcars) + aes(x=mpg, y=disp) + geom_point()
```
```{r}
ggplot(mtcars, aes(mpg, disp)) + geom_point()
```

```{r}
cars
```

```{r}
head(cars)
```

3 layers of ggplot - *Data* - *Aes* - *Geoms*

```{r}
ggplot(data=cars) + aes(x=speed,y=dist) + geom_point()
```

```{r}
ggplot(data=cars) + aes(x=speed,y=dist) + geom_point() + geom_line()
```

```{r}
ggplot(data=cars) + aes(x=speed,y=dist) + geom_point() + geom_smooth(method=lm, se=FALSE)
```

```{r}
ggplot(cars) + 
  aes(x=speed, y=dist) +
  geom_point() +
  labs(title="Speed and Stopping Distances of Cars",
       x="Speed (MPH)", 
       y="Stopping Distance (ft)",
       subtitle = "Your informative subtitle text here",
       caption="Dataset: 'cars'") +
  geom_smooth(method="lm", se=FALSE) +
  theme_bw()
```

```{r}
url <- "https://bioboot.github.io/bimm143_S20/class-material/up_down_expression.txt"
genes <- read.delim(url)
head(genes)
```

```{r}
gene_graph <- ggplot(genes) + 
    aes(x=Condition1, y=Condition2) +
    geom_point(color = "blue")
gene_graph
```

```{r}
gene_graph <- ggplot(genes) + 
    aes(x=Condition1, y=Condition2, col=State,alpha=0.3) +
    geom_point()+labs(title = "Gene experssion changes")
gene_graph
gene_graph + scale_color_manual(values = c("up" = "blue","down"="orange","unchanging"="grey")) 
```

```{r}
library(RColorBrewer)
display.brewer.all()
```

```{r}
gene_graph <- ggplot(genes) + 
    aes(x=Condition1, y=Condition2, col=State) +
    geom_point()+labs(title = "Gene experssion changes", x="Control (no drug) ",
         y="Drug Treatment")
gene_graph + scale_color_manual(values = brewer.pal(3,"Pastel1") )
```

```{r}
url <- "https://raw.githubusercontent.com/jennybc/gapminder/master/inst/extdata/gapminder.tsv"
gapminder <- read.delim(url)

library(dplyr)

gapminder_2007 <- gapminder %>% filter(year==2007)

```

```{r}
ggplot(gapminder_2007) +
  aes(x=gdpPercap, y=lifeExp) +
  geom_point()
```

```{r}
ggplot(gapminder_2007) +
  aes(x=gdpPercap, y=lifeExp,color=continent) +
  geom_point(alpha=0.5)
```

```{r}
ggplot(gapminder_2007) +
  aes(x=gdpPercap, y=lifeExp,color=continent,size=pop) +
  geom_point(alpha=0.5) + 
  scale_size_area(max_size = 10)
```

```{r}
ggplot(gapminder_2007) + 
  aes(x = gdpPercap, y = lifeExp, color = pop) +
  geom_point(alpha=0.8)
```

```{r}
gapminder_top5 <- gapminder %>% 
  filter(year==2007) %>% 
  arrange(desc(pop)) %>% 
  top_n(5, pop)

gapminder_top5
```
```{r}
ggplot(gapminder_top5) + 
  geom_col(aes(x = country, y = pop, fill=continent)) 
```


```{r}
USArrests$State <- rownames(USArrests)
ggplot(USArrests) +
  aes(x=reorder(State,Murder), y=Murder) +
  geom_col() +
  coord_flip()
```


